# SQLite Test Database Configuration
spring.datasource.url=jdbc:sqlite:test.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# Dummy Cloudinary Credentials to prevent context crash
cloudinary.cloud_name=test
cloudinary.api_key=test
cloudinary.api_secret=test